# Generated by Django 6.0.3 on 2026-04-16 08:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_cart_items_remove_order_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='category_slug',
            field=models.CharField(blank=True, editable=False, max_length=20, verbose_name='Слаг категории'),
        ),
        migrations.AddField(
            model_name='flower',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Новинка'),
        ),
        migrations.AddField(
            model_name='flower',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Популярный товар'),
        ),
        migrations.AddField(
            model_name='flower',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Старая цена'),
        ),
        migrations.AddField(
            model_name='flower',
            name='reviews',
            field=models.IntegerField(default=0, verbose_name='Количество отзывов'),
        ),
        migrations.AlterField(
            model_name='flower',
            name='category',
            field=models.CharField(choices=[('romantic', 'Романтические'), ('wedding', 'Свадебные'), ('spring', 'Весенние'), ('birthday', 'День рождения'), ('business', 'Деловые')], default='romantic', max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='flower',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='flower',
            name='stock',
            field=models.IntegerField(default=10, verbose_name='В наличии'),
        ),
    ]
